### PR TITLE
Use SparseTabularMDP from POMDPModelTools

### PR DESCRIPTION
**Pull request by MaximeBouton**
- Use SparseTabularMDP
- solve methods only for MDP

TODO: add a warning for POMDPs?

### CODE REVIEW

**Comment by MaximeBouton** [comment]
Restart travis after JuliaRegistries/General#2643 gets merged

**Comment by MaximeBouton** [comment]
The build fails in 0.7, I think we can safely drop the support.
Any objections @zsunberg @rejuvyesh ?

**Comment by mykelk** [comment]
Sounds good to me.

**Comment by zsunberg** [comment]
> The build fails in 0.7, I think we can safely drop the support.
> Any objections @zsunberg @rejuvyesh ?

drop it!

**Pull request merged**
